print("What food items will you like to order?")
item1 = input("Order 1: ")
item2 = input("Order 2: ")
item3 = input("Order 3: ")
# item1, item2, item3 = input("Kindly input your 3 favourite food items: ").split()
print()
print("Order confirmation! You have ordered: ")
print(item1)
print(item2)
print(item3)